Locale: en
CompatibilityMode: true
SinkRateTicks: 20
SinkCheckTicks: 100
TracerRateTicks: 5
PilotTool: 280
WorldGuardBlockMoveOnBuildPerm: true
WorldGuardBlockSinkOnPVPPerm: true
ManOverBoardTimeout: 30
FireballLifespan: 6
FireballPenetration: true
DisableSpillProtection: false
RequireCreatePerm: false
TNTContactExplosives: true
DisableCrates: false
FadeWrecksAfter: 0
RepairTicksPerBlock: 10
RepairMoneyPerBlock: 10
BlockQueueChunkSize: 1000
AllowCrewSigns: true
WGCustomFlagsUsePilotFlag: false
WGCustomFlagsUseMoveFlag: false
WGCustomFlagsUseRotateFlag: false
WGCustomFlagsUseSinkFlag: false
TownyBlockMoveOnSwitchPerm: false
TownyBlockSinkOnNoPVP: true
TownyWorldHeightLimits:
  world:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  world2:
    worldMin: -1
    worldMax: -1
    underTownSpawn: 255
    aboveTownSpawn: 96
  world_nether:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  world_the_end:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  frontier:
    worldMin: -1
    worldMax: -1
    underTownSpawn: 255
    aboveTownSpawn: 96
  flatworld:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  wilds:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  CakeVSPie:
    worldMin: -1
    worldMax: -1
    underTownSpawn: 255
    aboveTownSpawn: 96
  sensfortress:
    worldMin: -1
    worldMax: -1
    underTownSpawn: 255
    aboveTownSpawn: 96
  newworld_the_end:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  newworld:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  newworld_nether:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  hardcore:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  VoidWorldEnd:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  VoidWorld:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  VoidWorldHell:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  hardcoretest:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  VoidWorld2:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  Dungeons:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  BACKUP_world:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  test:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  OldRegionFiles:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
  plotworld:
    underTownSpawn: 255
    worldMin: -1
    aboveTownSpawn: 96
    worldMax: -1
DurabilityOverride: {}
